### ISSUE TITLE
Fire event on keypress/keydown

### ISSUE THREAD

**Issue by Spoowy** [synrc/n2o#300]
Hello,

what are some ways to go about firing events on keypresses(e.g. submit a form when a user hits enter while focussing on an input that belongs to the corresponding form)?

Also what about triggering events when hotkeys are being pressed(outside the scope of a form element) such as "CMD+S"?

I'm fairly new to N2O and Erlang(not so much to JavaScript and various other programming languages - python, php, java etc.).

Cheers,
Erwin

**Comment by doxtop** [comment]
It's unclear what you expect from the framework here. You have an events in javascript and you also have  an ability to wire postback to any of this events. So its up to you how to implement your application logic.

In nitro DSL, you can render #input{} element with `onkeypress`  attributes and call any javascript function on it.

By default postback in element will be wired to `click` event, but as I said before you are free to wire it on any event.  So for  example you can attach postback to keypress event like below

```
#input{id=i1}

wf:wire(#event{postback= <<"key">>, type=keypress, target= i1, delegate=?MODULE})
```

and catch the results in 

```
event(key) -> wf:info(?MODULE, "keypress", []);
```

Since its not an issue Its probably better to ask question in our telegram channel https://t.me/n2o_space so you will get the response faster.

**Comment by Spoowy** [comment]
@doxtop I tried to join the channel but it seems to not exist on my telegram.

Thank you for your reply! It helped me. 
I get an event triggered! It works flawlessly.

Is it possible to also get more information about the key that was pressed in the event?

Cheers,
Erwin

**Comment by 5HT** [comment]
Try https://t.me/erlang_n2o

**Comment by doxtop** [comment]
You have all information on JS side. So in case you are really need the full UI event information, you should wire JS function and  form message to the server accordingly. You can use the existing protocols or create your own. 

In case of nitro #event the answer is no. Message to server will be formed only with information you've put in postback.  You can have some extra information by querying values of element in `source` attribute of event. But this will work with html elements, particularly with they values and not with JS events.

I hardly can imagine someone will event need to reimplement all DOM API on sever. 
The keys with values can be queried with `source` attribute, different meta information mostly useless on server. in case you've complex custom control you will need the js implementation and protocol anyway. to check that something changed and query that value you can bind to `onchange` event. 

Probably you've good example why someone will need more that the element values, so you're welcome to share it and we will continue.

Sorry for inconvenience but the telegram channel was accidentally deleted :(
